version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: fivejars_db
    restart: unless-stopped
    env_file:
      - .env # Load environment variables from .env file (local)
    environment:
      MYSQL_ROOT_PASSWORD: ${FIVEJARS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${FIVEJARS_MYSQL_DATABASE}
      MYSQL_USER: ${FIVEJARS_MYSQL_USER}
      MYSQL_PASSWORD: ${FIVEJARS_MYSQL_USER_PASSWORD}
    ports:
      - "3307:3306" # Changed to 3307 to avoid conflict with local MySQL
    volumes:
      - fivejars_db_volume:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

      # Development only
      - ./db/testdata.sql:/docker-entrypoint-initdb.d/02-testdata.sql:ro


  backend:
    build: .
    container_name: fivejars_backend
    restart: unless-stopped
    env_file:
      - .env # Load environment variables from .env file (local)
    depends_on:
      - db
    ports:
      - "5000:5000" # Host port 5000 = Container port 5000

volumes:
  fivejars_db_volume:
