spring:
  application:
    name: spring_api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/five_jars_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:dev_password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: filesystem:../../infrastructure/db/migrations,filesystem:../../infrastructure/db/seeds

  jackson:
    # camelCase(Java) -> snake_case(JSON)
    property-naming-strategy: SNAKE_CASE
    # allow extra fields on requests
    deserialization:
      fail-on-unknown-properties: false

app:
  cors:
    allowed-origins:
      - "http://localhost:*"  # Any app on the host machine
      - "http://127.0.0.1:*"
      - "http://10.0.2.2:*"  # Standard for Android emulators
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
